<?php
namespace BtyBugHook\NewStudio\Repository;

use Btybug\btybug\Repositories\GeneralRepository;
use BtyBugHook\NewStudio\Models\NewStudios;

class NewStudiosRepository extends GeneralRepository
{
    /**
     * @return mixed
     */

    protected function model()
    {
        return new NewStudios();
    }

    public function delete(int $id)
    {
        $studio=$this->model()->find($id);
        $path = plugins_path(
            'vendor' . DS .
            'btybug.hook' . DS .
            'newstudio' . DS .
            'src' . DS .
            'storage' . DS .
            'studios' . DS .
            $studio->group . DS .
            $studio->type.DS.
            $studio->name.'.blade.php');
        if(\File::exists($path)){
            \File::delete($path);
        }
        $imgPath= public_path('images'.DS.'new_studios'.DS.$studio->image);
        if(\File::exists($imgPath)){
            \File::delete($imgPath);
        }
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}